services:
  - type: web
    name: filevault-backend
    runtime: docker
    region: oregon
    plan: free
    autoDeploy: true
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_OPTS
        value: -Xmx512m
